---
apiVersion: v1
kind: Service
metadata:
  name: dahantc-exporter
  namespace: mod-5gucp
  labels:
    app: dahantc-exporter
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 31888
      name: metrics
  selector:
    app: dahantc-exporter
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dahantc-exporter
  namespace: mod-5gucp
spec:
  selector:
    matchLabels:
      app: dahantc-exporter
  replicas: 1
  template:
    metadata:
      labels:
        app: dahantc-exporter
    spec:
      containers:
        - name: dahantc-exporter
          image: 172.18.1.157/public/dahantc-exporter:v1
          imagePullPolicy: Always
          ports:
            - containerPort: 80
              name: port
              protocol: TCP
            - containerPort: 22
              name: ssh
              protocol: TCP
          volumeMounts:
            - name: k8s-config
              mountPath: /root/.kube/config
          resources: {}
          lifecycle:
            postStart:
              exec:
                command:
                  [
                    "/bin/bash",
                    "/home/k8s/k8s_init/k8s_init/yaml/test/prep_test_env.sh",
                  ]
      volumes:
        - name: k8s-config
          secret:
            secretName: dahantc-exporter-k8s-config
      dnsConfig:
        nameservers:
          - 223.5.5.5
